services:
  test:
    build:
      dockerfile: Dockerfile
      context: .
    restart: no
    command: make test
    volumes:
      - ./:/opt/vom
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
