name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  tests:
    name: 'Tests on ${{ matrix.php }} (deps=${{ matrix.deps }}, symfony=${{ matrix.symfony }})'
    runs-on: ubuntu-latest

    env:
      SYMFONY_DEPRECATIONS_HELPER: 'max[self]=0'

    strategy:
      matrix:
        # Test the latest stable release
        php: [8.1] #[8.1, 8.2, 8.3]
        deps: [stable]
        symfony: ['^7.0']
        include:
          # Test lowest dependencies
          #- php: 8.1
          #  deps: lowest
          #  symfony: '^6.1'

          # Test LTS php/Symfony
          - php: 8.2
            deps: stable
            symfony: '^7.0'

          # Test latest php/Symfony
          #- php: 8.3
          #  deps: stable
          #  symfony: '^7.0'

    steps:
      - name: Checkout code
        uses: 'actions/checkout@v3'

      - name: Install PHP with extensions
        uses: 'shivammathur/setup-php@v2'
        with:
          coverage: none
          php-version: '${{ matrix.php }}'
          tools: 'composer:v2, flex'

      - name: Configure Symfony version
        run: 'echo SYMFONY_REQUIRE="${{ matrix.symfony }}" >> $GITHUB_ENV'

      - name: Allow dev dependencies
        run: 'composer config minimum-stability dev'

      - name: Composer install
        uses: 'ramsey/composer-install@v2'
        with:
          dependency-versions: '${{ matrix.deps }}'
          composer-options: '--prefer-dist'

      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit install

      - name: Run tests
        run: vendor/bin/simple-phpunit

  cs:
    name: 'Code Style'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.0.0
        with:
          args: --diff --dry-run